In [2]:
import numpy as np

In [ ]:
# det()
A = np.array([[1,2],
              [3,4]])
              
det_a = np.linalg.det(A)
print(det_a)

-2.0000000000000004


In [59]:
# inverse
import numpy as np
A = np.array([[1,0,0],
              [0,-1,0],
              [0, 0,-1]])
# A = np.array([[1, -2, 2],
#               [-3, 3, 0],
#               [4, 0, -4]])
inv_a = np.linalg.inv(A)
print(np.linalg.det(A))
print(np.linalg.det(inv_a))

# print(A@inv_a)
print(inv_a)
print(A.T)

# print(A@inv_a,)
# print("the det,", np.linalg.det(A))


1.0
1.0
[[ 1.  0.  0.]
 [-0. -1. -0.]
 [-0. -0. -1.]]
[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]


In [ ]:
# adjugates
adj_a = np.linalg.det(A) * np.linalg.inv(A)
print(adj_a)

[[ 4. -2.]
 [-3.  1.]]


In [ ]:
# exam the calculation, A @ A-1

print(inv_a@A)
print(A@inv_a)

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [9]:
# identity M
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
import sympy as sp
import numpy as np

def diagonalization_sympy(matrix_list):
    A = sp.Matrix(matrix_list)
    print("Matrix A:")
    # sp.pprint(A)
    print(np.array(A))

    eigen_info = A.eigenvects()
    
    P_cols = []
    D_diag = []
    
    is_diagonalizable = True
    n = A.shape[0]
    total_vectors = 0

    for lam, alg_mult, vecs in eigen_info:
        geo_mult = len(vecs)
        print(f"λ={lam}: algebraic={alg_mult}, geometric={geo_mult}")
        
        if geo_mult != alg_mult:
            print(f"  ⚠️ Warning: λ={lam} has geometric {geo_mult} != algebraic {alg_mult}")
        
        for v in vecs:
            D_diag.append(lam)
            P_cols.append(v)
            total_vectors += 1

    if total_vectors == n:
        print("✅ Diagonalizable (SymPy)")
        P, D = A.diagonalize() 
        
        print("P (Eigenvectors matrix - Integers!):")
        print(np.array(P))

        print("D (Eigenvalues matrix):")
        print(np.array(D))

        print("P_inv (Inverse of P):")
        P_inv = P.inv()
        print(np.array(P_inv))

        res = P * D * P_inv
        if res == A:
            print("✅ Verified: Perfect Match")
        else:
            print("❌ Mismatch")
            
    else:
        print("❌ NOT diagonalizable")

AA = [
    [2, -3, 1, -1], 
    [-2, -2, 2, 3], 
    [0, -3, -1, -3],
    [2, 1, -1, -2]
]
A3 = [
    [1,0, 1], 
    [0,1,0], 
    [0,0,-3],
]
# A = np.array([[2, -3, 1, -1], 
#                 [-2, -2, 2, 3], 
#                 [0, -3, -1, -3],
#                 [2, 1, -1, -2]], dtype=float)

diagonalization_sympy(AA)

Matrix A:
[[2 -3 1 -1]
 [-2 -2 2 3]
 [0 -3 -1 -3]
 [2 1 -1 -2]]
λ=-4: algebraic=1, geometric=1
λ=-1: algebraic=1, geometric=1
λ=0: algebraic=1, geometric=1
λ=2: algebraic=1, geometric=1
✅ Diagonalizable (SymPy)
P (Eigenvectors matrix - Integers!):
[[-1 0 1 4]
 [-3 -1 -1 -1]
 [-1 -2 -3 -1]
 [2 1 2 2]]
D (Eigenvalues matrix):
[[-4 0 0 0]
 [0 -1 0 0]
 [0 0 0 0]
 [0 0 0 2]]
P_inv (Inverse of P):
[[-1/6 -1/12 1/4 5/12]
 [2/3 -5/3 -1 -8/3]
 [-1/2 5/4 1/4 7/4]
 [1/3 -1/3 0 -1/3]]
✅ Verified: Perfect Match


In [60]:
A = np.array([[2, -3, 1, -1], 
                [-2, -2, 2, 3], 
                [0, -3, -1, -3],
                [2, 1, -1, -2]], dtype=float)
print("det: ",np.linalg.det(A))

inv_a = np.linalg.inv(A)
print("inv_a: ",np.linalg.det(inv_a))

det:  -5.551115123125763e-16


LinAlgError: Singular matrix