In [1]:
import numpy as np

def decompose_S_K(A):
    if A.shape[0] != A.shape[1]:
        print("錯誤：必須是方陣 (n x n) 才能拆解！")
        return None, None

    A_T = A.T
    
    S = (A + A_T) / 2  # 對稱部分
    K = (A - A_T) / 2  # 反對稱部分
    
    print("=== 原始矩陣 A ===")
    print(A)
    print("\n=== 拆解出的 S (對稱) ===")
    print(S)
    print("\n=== 拆解出的 K (反對稱，對角線必為0) ===")
    print(K)
    
    reconstructed = S + K
    if np.allclose(A, reconstructed):
        print("\n✅ 驗證成功：S + K 完全等於 A")
    else:
        print("\n❌ 驗證失敗")
        
    return S, K

A = np.array([
    [1, 2,3],
    [4,5,6],
    [7,8, 9]
], dtype=float)

decompose_S_K(A)

print('Symmetric (對稱矩陣)：矩陣轉置後等於它自己 (A^T = A)\nSkew-Symmetric (反對稱矩陣)：矩陣轉置後等於它的負號 (A^T = -A)')
print("S = (A + A^T)/2, W = (A - A^T)/2")

=== 原始矩陣 A ===
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

=== 拆解出的 S (對稱) ===
[[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]

=== 拆解出的 K (反對稱，對角線必為0) ===
[[ 0. -1. -2.]
 [ 1.  0. -1.]
 [ 2.  1.  0.]]

✅ 驗證成功：S + K 完全等於 A
Symmetric (對稱矩陣)：矩陣轉置後等於它自己 (A^T = A)
Skew-Symmetric (反對稱矩陣)：矩陣轉置後等於它的負號 (A^T = -A)
S = (A + A^T)/2, W = (A - A^T)/2


In [5]:
A = np.array([
    [1, 5, -2],
    [3, 4, 8],
    [-5, 2, 9]
], dtype=float)

print(A.T)

[[ 1.  3. -5.]
 [ 5.  4.  2.]
 [-2.  8.  9.]]
