In [2]:
import numpy as np

In [ ]:
# det()
A = np.array([[1,2],
              [3,4]])
              
det_a = np.linalg.det(A)
print(det_a)

-2.0000000000000004


In [4]:
# inverse

A = np.array([[4,1],
              [3,2]])
inv_a = np.linalg.inv(A)
print(inv_a)

[[ 0.4 -0.2]
 [-0.6  0.8]]


In [ ]:
# adjugates
adj_a = np.linalg.det(A) * np.linalg.inv(A)
print(adj_a)

[[ 4. -2.]
 [-3.  1.]]


In [ ]:
# exam the calculation, A @ A-1

print(inv_a@A)
print(A@inv_a)

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [9]:
# identity M
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
import sympy as sp
import numpy as np

def diagonalization_sympy(matrix_list):
    A = sp.Matrix(matrix_list)
    print("Matrix A:")
    # sp.pprint(A)
    print(np.array(A))

    eigen_info = A.eigenvects()
    
    P_cols = []
    D_diag = []
    
    is_diagonalizable = True
    n = A.shape[0]
    total_vectors = 0

    for lam, alg_mult, vecs in eigen_info:
        geo_mult = len(vecs)
        print(f"λ={lam}: algebraic={alg_mult}, geometric={geo_mult}")
        
        if geo_mult != alg_mult:
            print(f"  ⚠️ Warning: λ={lam} has geometric {geo_mult} != algebraic {alg_mult}")
        
        for v in vecs:
            D_diag.append(lam)
            P_cols.append(v)
            total_vectors += 1

    if total_vectors == n:
        print("✅ Diagonalizable (SymPy)")
        P, D = A.diagonalize() 
        
        print("P (Eigenvectors matrix - Integers!):")
        print(np.array(P))

        print("D (Eigenvalues matrix):")
        print(np.array(D))

        print("P_inv (Inverse of P):")
        P_inv = P.inv()
        print(np.array(P_inv))

        res = P * D * P_inv
        if res == A:
            print("✅ Verified: Perfect Match")
        else:
            print("❌ Mismatch")
            
    else:
        print("❌ NOT diagonalizable")

A_repeat_pass = [
    [3, 0, 0, 0],
    [0, 3, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]
A_fail_4x4 = [
    [2, 1, 0, 0],
    [0, 2, 0, 0], # 這裡導致缺向量
    [0, 0, 5, 0],
    [0, 0, 0, 5]
]
A_det_zero = [
    [2, 0, 0, 0],
    [0, 3, 0, 0],
    [0, 0, 1, 0],
    [1, 1, 1, 0] 
]
diagonalization_sympy(A_repeat_pass)

Matrix A:
[[3 0 0 0]
 [0 3 0 0]
 [0 0 1 0]
 [0 0 0 1]]
λ=1: algebraic=2, geometric=2
λ=3: algebraic=2, geometric=2
✅ Diagonalizable (SymPy)
P (Eigenvectors matrix - Integers!):
[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]
D (Eigenvalues matrix):
[[1 0 0 0]
 [0 1 0 0]
 [0 0 3 0]
 [0 0 0 3]]
P_inv (Inverse of P):
[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]
✅ Verified: Perfect Match


In [ ]:
# import numpy as np

# # =========================
# # 範例 1：驗證 eigenvector
# # =========================

# A1 = np.array([
# [1, 0, 0],
#     [1, 2, 0],
#     [0, 1, 3]
# ], dtype=float)

# x = np.array([16, 4, 1], dtype=float)

# Ax = A1 @ x
# lam_col = Ax / x

# print("Ax =", Ax)
# print("lam_col =",lam_col)
# print("λ =", lam_col[0])
# print("Is eigenvector?", np.allclose(Ax, lam_col[0] * x))


# # # =========================
# # # 範例 2：驗證 eigenvalue
# # # =========================

# A2 = np.array([
# [1, 0, 0],
#     [1, 2, 0],
#     [0, 1, 3]
# ], dtype=float)

# lam_test = 3
# I = np.eye(A2.shape[0])

# print("\nExample 2")
# print("det(A - λI) =", np.linalg.det(A2 - lam_test * I))
# print("Is eigenvalue?", np.isclose(np.linalg.det(A2 - lam_test * I), 0))
# # 用det 0 檢驗的理由：
# # 這個齊次系統有沒有 非零解？有沒有 x 不為0的解？（因為 0 解我們不要）
# # if 有，一定不可逆，means, det() = 0


# # # =========================
# # # 直接算 eigenvalues / eigenvectors
# # # =========================
# A4 = np.array([
# [1, 0, 0],
#     [1, 2, 0],
#     [0, 1, 3]
# ], dtype=float)
# vals, vecs = np.linalg.eig(A4)

# print("\nEigen-decomposition of A1")
# print("Eigenvalues:", vals) # 有多個 lambda 也能吐出來
# print("Eigenvectors (columns):\n", vecs)

Ax = [16. 24.  7.]
lam_col = [1. 6. 7.]
λ = 1.0
Is eigenvector? False

Example 2
det(A - λI) = 0.0
Is eigenvalue? True

Eigen-decomposition of A1
Eigenvalues: [3. 2. 1.]
Eigenvectors (columns):
 [[ 0.          0.          0.66666667]
 [ 0.          0.70710678 -0.66666667]
 [ 1.         -0.70710678  0.33333333]]


In [ ]:
# # 前提都是 A 是方正，且 det(A) 不等0

# A = np.array([
#     [2,1,-1],
#     [1,0,1],
#     [1,1,-2]
#     # [1, 2, 4, 8],
#     # [1, 3, 9, 27]
# ], dtype=float)

# b = np.array([0,1,-3], dtype=float)

# x_1 = np.linalg.solve(A.T, b)
# x_1 = np.round(x_1, 6)

# print(x_1)


# # 下面的好像不常用了
# # x_2 = np.linalg.inv(A) @ b
# # x_2 = np.round(x_2, 6)

# # print(x_2)

LinAlgError: Singular matrix

In [5]:
# import numpy as np

# A3 = np.array([
#     [1, -2, 3],
#     [2, 6, -6],
#     [1, 2, -1]
# ], dtype=float)
# A4 = np.array([
#     [1,0,1],
#     [0,1,0],
#     [0,0,-3]
# ], dtype=float)

# def diagonalization(the_m):
#     eig_vals, eig_vecs = np.linalg.eig(the_m)

#     # 合併 eigenvalues
#     eig_vals_r = np.round(eig_vals.real, 6)
#     # print("eigenvalues (rounded):", eig_vals_r)
#     unique = np.unique(eig_vals_r)
#     print("unique eigenvalues:", unique)

#     # 檢查每個 λ 的 eigenvectors 數量
#     n = the_m.shape[0]
#     geo_total = 0

#     for lam in unique:
#         M = the_m - lam * np.eye(n)
#         geo = n - np.linalg.matrix_rank(M)
#         alg = np.sum(eig_vals_r == lam)
#         print(f"λ={lam}: algebraic={alg}, geometric={geo}")
#         # algebraic =「這個 λ 佔了幾個位置」
#         # geometric =「真的能拿來當 basis 的方向有幾個」
#         geo_total += geo

#     # 判斷是否可對角化
#     if geo_total == n:
#         print("✅ Diagonalizable\n\n")

#         P = eig_vecs
#         D = np.diag(eig_vals)
#         Pinv = np.linalg.inv(P)

#         print("P: \n", P)
#         print("D: \n", D)
#         print("Pinv: \n", Pinv)
#         print("\nP @ D @ Pinv\n", P @ D @ Pinv)
#         print("Final check: ",np.allclose(the_m, P @ D @ Pinv))

#     else:
#         print("❌ NOT diagonalizable")
# diagonalization(A4)

unique eigenvalues: [-3.  1.]
λ=-3.0: algebraic=1, geometric=1
λ=1.0: algebraic=2, geometric=2
✅ Diagonalizable


P: 
 [[ 1.          0.         -0.24253563]
 [ 0.          1.          0.        ]
 [ 0.          0.          0.9701425 ]]
D: 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -3.]]
Pinv: 
 [[1.         0.         0.25      ]
 [0.         1.         0.        ]
 [0.         0.         1.03077641]]

P @ D @ Pinv
 [[ 1.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  0. -3.]]
Final check:  True
