In [2]:
import numpy as np

In [26]:
import numpy as np
import sympy

A = np.array([
    [-1, 1, 1],
    [0, 1, 3],
    [1, 1, 5],
], dtype=float)

# --- 1. 先檢查 Determinant ---
det = np.linalg.det(A)

# 判斷 Det 是否 "不等於" 0 (考慮浮點數誤差，用 isclose 判斷是否等於 0)
if not np.isclose(det, 0):
    print(f"Det = {det:.2f} (非 0)，矩陣滿秩。")
    print("結論：只有零解 x = [0, 0, 0]")
    
else:
    print(f"Det = {det:.2f} (接近 0)，矩陣奇異。")
    print("結論：存在非零解，開始計算...")

    # --- 2. Det == 0 才做 SVD 解算 ---
    U, S, Vt = np.linalg.svd(A)
    x = Vt[-1]  # 取最後一個向量 (對應奇異值為 0 的那個)
    
    # 你的縮放邏輯 (以最後一個元素歸一化並轉整數)
    # 稍微加個防呆，怕 x[2] 剛好是 0 導致除以 0
    if np.isclose(x[2], 0):
        print("注意：最後一個分量為 0，無法當作縮放基準，印出原始 SVD 解：")
        print(x)
    else:
        x_int = np.round(x / x[2]).astype(int)
        print("整數解 x:", x_int)
        
        # 驗證
        print("驗證 Ax (應該全是 0):", A @ x_int)

Det = 0.00 (接近 0)，矩陣奇異。
結論：存在非零解，開始計算...
整數解 x: [-2 -3  1]
驗證 Ax (應該全是 0): [0. 0. 0.]


In [3]:
import numpy as np
import sympy

def solve_and_show_rref(A):
    det = np.linalg.det(A)
    print(f"原本矩陣 A:\n{A}")
    print(f"Determinant: {det:.2f}")
    print("-" * 20)

    rref_matrix = np.array(sympy.Matrix(A).rref()[0]).astype(float)

    if not np.isclose(det, 0):
        print("【情況：滿秩 (Full Rank)】")
        print(rref_matrix)
        print("\n結論：變數完全獨立，x 只能是 [0 0 0]")
        
    else:
        print("【情況：奇異 (Singular)】")
        print(rref_matrix)
        print("\n結論：因為有全 0 列，存在非零解 (如下)：")
        
        U, S, Vt = np.linalg.svd(A)
        x = Vt[-1]
        
        if not np.isclose(x[2], 0):
            x_int = np.round(x / x[2]).astype(int)
            print("整數解 x:", x_int)
        else:
            print("原始解 x:", x)


print("=== 測試 1 (Det != 0) ===")
A_full = np.array([[-1, 1, 1], 
                   [0, 1, 3], 
                   [1, 1, 0]], dtype=float)
solve_and_show_rref(A_full)

print("=== 測試 2 (Det == 0) ===")
A_zero = np.array([[-1, 1, 1], 
                   [0, 1, 3], 
                   [1, 1, 5]], dtype=float)
solve_and_show_rref(A_zero)

=== 測試 1 (Det != 0) ===
原本矩陣 A:
[[-1.  1.  1.]
 [ 0.  1.  3.]
 [ 1.  1.  0.]]
Determinant: 5.00
--------------------
【情況：滿秩 (Full Rank)】
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

結論：變數完全獨立，x 只能是 [0 0 0]
=== 測試 2 (Det == 0) ===
原本矩陣 A:
[[-1.  1.  1.]
 [ 0.  1.  3.]
 [ 1.  1.  5.]]
Determinant: 0.00
--------------------
【情況：奇異 (Singular)】
[[1. 0. 2.]
 [0. 1. 3.]
 [0. 0. 0.]]

結論：因為有全 0 列，存在非零解 (如下)：
整數解 x: [-2 -3  1]
