## Assignment 2, Detecting Anomalous Users via Access Patterns

---


#### Subproblem 1.

1. The process counted by hand will be as below.

    Lets take $i = 1$, $j = 2$ for example. Finding the similarity between $u1$ and $u2$.

    $
    s_{12} = \sum_{k=1}^{5} u_{1k} u_{2k}
    $

    $
    s_{12} = u_{11} u_{21} + u_{12} u_{22} + u_{13} u_{23} + u_{14} u_{24} + u_{15} u_{25}
    $

    The result of $s_{12}$ will be, $ 3*4 + 5*5 + 2*3 + 0*0 + 0*0 = 43$


2. We can use the $dot()$ function in numpy to count the Cartesian product more easily. Since we are counting all the similarity of users in the matrix.


In [3]:
import numpy as np

U = np.array([
    [3, 5, 2, 0, 0],
    [4, 5, 3, 0, 0],
    [5, 4, 3, 0, 0],
    [1, 0, 1, 6, 2],
    [4, 5, 3, 0, 0],
    [5, 4, 1, 1, 0]
])

S = U @ U.T
print(S)

[[38 43 41  5 43 37]
 [43 50 49  7 50 43]
 [41 49 50  8 49 44]
 [ 5  7  8 42  7 12]
 [43 50 49  7 50 43]
 [37 43 44 12 43 43]]


3. $S$ will be a symmetric matrix, because it contains both pairs such as u1*u2 and u2*u1, which offering the same value. The main diagonal of $S$ wil be the relation of themselves, $u_{11}, u_{22}, u_{33},...$

    <!-- is the result of all the combination in matrix U, $S = UU^{T}$.  -->

    User 2 and user 5 have the most similarity with a value of $50$, user 1 and user 4 have the least similarity with a value of $5$.

    Base on $S$, we can notice there is a huge difference on the similarity of user 4 with all the users. By scanning through all the rows in $S$, we always get the lowest value with user 4. As we can see on row4 of $U$, $[ 5, 7, 8, 42,  7, 12]$.

    As a result, we can simply make 2 groups, $[1, 2, 3, 5, 6]$ and $[4]$.

---

#### Subproblem 2.

1. U_drop and u_7 as below.


In [17]:
U_drop = np.array([
    [3, 5, 2, 0],
    [4, 5, 3, 0],
    [5, 4, 3, 0],
    [1, 0, 1, 2],
    [4, 5, 3, 0],
    [5, 4, 1, 0]
])

u_7_drop = np.array([[4], 
                [5], 
                [0], 
                [0]])

2. The least-squares of x.     
    
    I take $np.round()$ to make the result of $x$ more easy to read.

In [24]:
x = U_drop @ np.linalg.inv(U_drop.T @ U_drop) @ u_7_drop
# (6, 4) @ (4, 4) @ (4, 1)

print(np.round(x, 5))

[[ 0.86792]
 [-0.12683]
 [-0.72851]
 [-0.     ]
 [-0.12683]
 [ 1.21069]]


3. Use the estimated x together with the original matrix U to approximate the missing access frequency in u7.

In [26]:
u7 = x.T @ U

print(np.round(u7, 5))

[[ 4.       5.       0.       1.21069 -0.     ]]


4. Compare the completed vector u7 to the existing user patterns from Subproblem 1. Which group of users does the new user most closely resemble?

    We can get u7's relationship with each user by adding it into the new U array, and calculate the new S to see how it react with different user.

    Base on the result, we can add u7 to group $[1, 2, 3, 5, 6]$. Since we find the similar pattern as we saw at the original $U$, the similarity of u4 and u7 acted just as how u4 with group $[1, 2, 3, 5, 6]$.

    Row4 of new_U is still the least consistent row, $ [ 5, 7, 8, 42, 7, 12, 11.26414]$.

In [32]:
new_U = np.array([
    [3, 5, 2, 0, 0],
    [4, 5, 3, 0, 0],
    [5, 4, 3, 0, 0],
    [1, 0, 1, 6, 2],
    [4, 5, 3, 0, 0],
    [5, 4, 1, 1, 0],
    [4, 5, 0, 1.21069, -0]
])

new_S = new_U @ new_U.T
print(np.round(new_S, 5))

[[38.      43.      41.       5.      43.      37.      37.     ]
 [43.      50.      49.       7.      50.      43.      41.     ]
 [41.      49.      50.       8.      49.      44.      40.     ]
 [ 5.       7.       8.      42.       7.      12.      11.26414]
 [43.      50.      49.       7.      50.      43.      41.     ]
 [37.      43.      44.      12.      43.      43.      41.21069]
 [37.      41.      40.      11.26414 41.      41.21069 42.46577]]
